name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Instalar y Validar Código (Lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Obtener caché de dependencias
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar Linter en el monorepo
        # Esto ejecutará ESLint/Prettier según lo definido en turbo.json
        run: pnpm run lint